- name: Install pip
  apt:
      name: python3-pip
      state: latest
      update_cache: yes

- name: Install docker libraries
  pip:
    name: 
      - docker==6.1.3
      - docker-compose
    state: present